name: M-RPG
version: '${project.version}'
main: pl.majkus522.mrpg.Main
api-version: 1.20

commands:
  login:
    description: Login
    usage: /<command> <password>

  skills:
    description: Check your skills
    usage: /<command>

  status:
    description: Check your status
    usage: /<command>

  shout:
    description: Shout your speach
    usage: /<command> <text>