name: M-RPG
version: '${project.version}'
main: pl.majkus522.mrpg.Main
api-version: 1.20

commands:
  login:
    description: Login
    usage: /<command> <password>

  skills:
    description: Check your skills
    usage: /<command>

  status:
    description: Check your status
    usage: /<command>

  shout:
    description: Shout your speach
    usage: /<command> <text>

  entity:
    description: Spawn entity
    usage: /<command>
    permission: op

  pay:
    description: Pay someone money
    usage: /<command> <player> <amount>

  world:
    description: Teleport between worlds
    usage: /<command> <world>
    permission: op

  taunt:
    description: Taunt enemies
    usage: /<command>